UCS_Backend: UCS_Backend.Repositories.RoomRepository Class Reference
UCS_Backend.Repositories.RoomRepository Class Reference
Creates a class for RoomRepositoty
Public Member Functions
RoomRepository (DataContext dataContext)
room repo added
Room Add (Room room)
add room and find room by ID
void Delete (Room entity)
be able to delete room
Room? FindById (int id)
be able to find room by ID passed
int FindRoomIdByName (string name)
be able to find room by name
List< ScheduleInfo > GetScheduleByRoomNumber (int roomNumber)
method to get schedule by room number in data context
List< ScheduleInfo > CheckCrossListedClasses (List< ScheduleInfo > scheduleInfos)
Creates schedule info
void Update (Room entity)
updates room
int GetRoomIdByRoomName (string buildingCode, string roomNumber)
int FindRoomIdByName (string name)
List< ScheduleInfo > GetScheduleByRoomNumber (int roomNumber)
int GetRoomIdByRoomName (string buildingCode, string roomNumber)
Public Member Functions inherited from UCS_Backend.Interfaces.IBaseRepository< Room >
T Add (T entity)
void Update (T entity)
void Delete (T entity)
T? FindById (int id)
Properties
IEnumerable< Room > GetAll [get]
Properties inherited from UCS_Backend.Interfaces.IBaseRepository< Room >
IEnumerable< T > GetAll [get]
Detailed Description
Creates a class for RoomRepositoty
Constructor & Destructor Documentation
RoomRepository()
UCS_Backend.Repositories.RoomRepository.RoomRepository (DataContext dataContext)
room repo added
Parameters
dataContext
Member Function Documentation
Add()
Room UCS_Backend.Repositories.RoomRepository.Add (Room room)
add room and find room by ID
Parameters
room
Returns
References UCS_Backend.Repositories.RoomRepository.FindRoomIdByName(), UCS_Backend.Models.Room.Name, and UCS_Backend.Data.DataContext.Rooms.
CheckCrossListedClasses()
List< ScheduleInfo > UCS_Backend.Repositories.RoomRepository.CheckCrossListedClasses (List< ScheduleInfo > scheduleInfos)
Creates schedule info
Parameters
scheduleInfos
Returns
Referenced by UCS_Backend.Repositories.RoomRepository.GetScheduleByRoomNumber().
Delete()
void UCS_Backend.Repositories.RoomRepository.Delete (Room entity)
be able to delete room
Parameters
entity
FindById()
Room? UCS_Backend.Repositories.RoomRepository.FindById (int id)
be able to find room by ID passed
Parameters
id
Returns
FindRoomIdByName()
int UCS_Backend.Repositories.RoomRepository.FindRoomIdByName (string name)
be able to find room by name
Parameters
name
Returns
Implements UCS_Backend.Interfaces.IRepositories.IRoomRepository.
Referenced by UCS_Backend.Repositories.RoomRepository.Add().
GetRoomIdByRoomName()
int UCS_Backend.Repositories.RoomRepository.GetRoomIdByRoomName (string buildingCode, string roomNumber)
Parameters
buildingCode
roomNumber
Returns
Implements UCS_Backend.Interfaces.IRepositories.IRoomRepository.
References UCS_Backend.Data.DataContext.Rooms.
GetScheduleByRoomNumber()
List< ScheduleInfo > UCS_Backend.Repositories.RoomRepository.GetScheduleByRoomNumber (int roomNumber)
method to get schedule by room number in data context
Parameters
roomNumber
Returns
Implements UCS_Backend.Interfaces.IRepositories.IRoomRepository.
References UCS_Backend.Repositories.RoomRepository.CheckCrossListedClasses(), and UCS_Backend.Models.SubModels.ScheduleInfo.StartTime.
Update()
void UCS_Backend.Repositories.RoomRepository.Update (Room entity)
updates room
Parameters
entity
Property Documentation
GetAll
IEnumerable<Room> UCS_Backend.Repositories.RoomRepository.GetAll get
The documentation for this class was generated from the following file:
UCS_Backend/Repositories/RoomRepository.cs