UCS_Backend: course_parser_v2 Namespace Reference
course_parser_v2 Namespace Reference
Functions
def validate_military_time (military_time)
def get_availability (room, day)
def convert_to_military (std_time)
def weekday_converter (shorthand)
def process_weekday_time_blocks ()
def process_files_base (files)
def process ()
def print_data (schedule, time_blockings, availability, roominfo)
def show_availabilities ()
Variables
dictionary courses = {}
dictionary weekday_time_blockings = {}
dictionary rooms = {}
courses_revised = None
dictionary file_name_groups
Function Documentation
convert_to_military()
def course_parser_v2.convert_to_military (std_time)
Referenced by process().
get_availability()
def course_parser_v2.get_availability (room, day)
References validate_military_time().
Referenced by show_availabilities().
print_data()
def course_parser_v2.print_data (schedule, time_blockings, availability, roominfo)
References show_availabilities().
Referenced by show_availabilities().
process()
def course_parser_v2.process ()
References convert_to_military(), and weekday_converter().
Referenced by show_availabilities().
process_files_base()
def course_parser_v2.process_files_base (files)
Referenced by show_availabilities().
process_weekday_time_blocks()
def course_parser_v2.process_weekday_time_blocks ()
Referenced by show_availabilities().
show_availabilities()
def course_parser_v2.show_availabilities ()
References get_availability(), print_data(), process(), process_files_base(), and process_weekday_time_blocks().
Referenced by print_data().
validate_military_time()
def course_parser_v2.validate_military_time (military_time)
Referenced by get_availability().
weekday_converter()
def course_parser_v2.weekday_converter (shorthand)
Referenced by process().
Variable Documentation
courses
dictionary course_parser_v2.courses = {}
courses_revised
course_parser_v2.courses_revised = None
file_name_groups
dictionary course_parser_v2.file_name_groups
Initial value:
=  {
    1: ['CSCI1191.csv', 'BIOI1191.csv', 'BMI1191.csv', 'CIST_EMIT1191.csv', 'CYBR1191.csv', 'ISQA1191.csv', 'ITIN1191.csv'],
    2: ['CSCI1191.csv', 'BIOI1191.csv', 'BMI1191.csv', 'CYBR1191.csv', 'ISQA1191.csv', 'ITIN1191.csv'],
    3: ['../../CSVFiles/CSCI1191.csv']
}
rooms
dictionary course_parser_v2.rooms = {}
weekday_time_blockings
dictionary course_parser_v2.weekday_time_blockings = {}