UCS_Backend: db_genalg.Class Class Reference
db_genalg.Class Class Reference
Public Member Functions
def __init__ (self, id, course)
def get_id (self)
def get_course (self)
def get_instructor (self)
def get_meetingTime (self)
def get_meetinDay (self)
def get_room (self)
def set_instructor (self, instructor)
def set_meetingTime (self, meetingTime)
def set_meetingDay (self, meetingDay)
def set_room (self, room)
def __str__ (self)
Constructor & Destructor Documentation
__init__()
def db_genalg.Class.__init__ (self, id, course)
References db_genalg.Class._course, db_genalg.Class._id, db_genalg.Class._instructor, db_genalg.Class._meetingDay, db_genalg.Class._meetingTime, and db_genalg.Class._room.
Member Function Documentation
__str__()
def db_genalg.Class.__str__ (self)
References db_genalg.Class._course.
get_course()
def db_genalg.Class.get_course (self)
get_id()
def db_genalg.Class.get_id (self)
get_instructor()
def db_genalg.Class.get_instructor (self)
Referenced by db_genalg.Schedule.get_blockings().
get_meetinDay()
def db_genalg.Class.get_meetinDay (self)
Referenced by db_genalg.Schedule.get_blockings().
get_meetingTime()
def db_genalg.Class.get_meetingTime (self)
Referenced by db_genalg.Schedule.get_blockings().
get_room()
def db_genalg.Class.get_room (self)
Referenced by db_genalg.Schedule.get_blockings().
set_instructor()
def db_genalg.Class.set_instructor (self, instructor)
set_meetingDay()
def db_genalg.Class.set_meetingDay (self, meetingDay)
set_meetingTime()
def db_genalg.Class.set_meetingTime (self, meetingTime)
set_room()
def db_genalg.Class.set_room (self, room)
The documentation for this class was generated from the following file:
UCS_Backend/Utils/Python/db_genalg.py