UCS_Backend: UCS_Backend.Interfaces.IIndividualRepository Interface Reference
UCS_Backend.Interfaces.IIndividualRepository Interface Reference
creates class for individual repo with task to get individuals
Public Member Functions
Task< List< Individual > > GetAllIndividuals ()
Task< Individual?> GetIndividualById (int id)
Task< Individual > AddIndividual (Individual individual)
Task<(bool, Individual)> UpdateIndividual (Individual individual)
Task< bool > DeleteIndividual (Individual individual)
Public Member Functions inherited from UCS_Backend.Interfaces.IBaseRepository< Individual >
T Add (T entity)
void Update (T entity)
void Delete (T entity)
T? FindById (int id)
Additional Inherited Members
Properties inherited from UCS_Backend.Interfaces.IBaseRepository< Individual >
IEnumerable< T > GetAll [get]
Detailed Description
creates class for individual repo with task to get individuals
Member Function Documentation
AddIndividual()
Task< Individual > UCS_Backend.Interfaces.IIndividualRepository.AddIndividual (Individual individual)
Implemented in UCS_Backend.Repositories.IndividualRepository.
Referenced by UCS_Backend.Controllers.IndividualController.AddIndividual().
DeleteIndividual()
Task< bool > UCS_Backend.Interfaces.IIndividualRepository.DeleteIndividual (Individual individual)
Implemented in UCS_Backend.Repositories.IndividualRepository.
Referenced by UCS_Backend.Controllers.IndividualController.DeleteIndividual().
GetAllIndividuals()
Task< List< Individual > > UCS_Backend.Interfaces.IIndividualRepository.GetAllIndividuals ()
Implemented in UCS_Backend.Repositories.IndividualRepository.
Referenced by UCS_Backend.Controllers.IndividualController.GetAllIndividuals().
GetIndividualById()
Task< Individual?> UCS_Backend.Interfaces.IIndividualRepository.GetIndividualById (int id)
Implemented in UCS_Backend.Repositories.IndividualRepository.
Referenced by UCS_Backend.Controllers.IndividualController.GetIndividualById().
UpdateIndividual()
Task<(bool, Individual)> UCS_Backend.Interfaces.IIndividualRepository.UpdateIndividual (Individual individual)
Implemented in UCS_Backend.Repositories.IndividualRepository.
Referenced by UCS_Backend.Controllers.IndividualController.UpdateIndividual().
The documentation for this interface was generated from the following file:
UCS_Backend/Interfaces/IRepositories/IIndividualRepository.cs