UCS_Backend: UCS_Backend.Interfaces.IRepositories.IClassRepository Interface Reference
UCS_Backend.Interfaces.IRepositories.IClassRepository Interface Reference
creates class for class repository to ad new class or find classID
Public Member Functions
int AddNewClass (ClassModel classModel)
int FindClssID (string catalogNumber, string section)
int GetClassIdByCourseAndSection (string courseNumber, string sectionNumber, string enrollment)
Detailed Description
creates class for class repository to ad new class or find classID
Member Function Documentation
AddNewClass()
int UCS_Backend.Interfaces.IRepositories.IClassRepository.AddNewClass (ClassModel classModel)
Implemented in UCS_Backend.Repositories.ClassRepository.
Referenced by UCS_Backend.Utils.CSVParser.process().
FindClssID()
int UCS_Backend.Interfaces.IRepositories.IClassRepository.FindClssID (string catalogNumber, string section)
Implemented in UCS_Backend.Repositories.ClassRepository.
Referenced by UCS_Backend.Utils.CSVParser.process().
GetClassIdByCourseAndSection()
int UCS_Backend.Interfaces.IRepositories.IClassRepository.GetClassIdByCourseAndSection (string courseNumber, string sectionNumber, string enrollment)
Implemented in UCS_Backend.Repositories.ClassRepository.
Referenced by UCS_Backend.Repositories.ScheduleRepository.AddClass().
The documentation for this interface was generated from the following file:
UCS_Backend/Interfaces/IRepositories/IClassRepository.cs