UCS_Backend: UCS_Backend.Controllers.ScheduleController Class Reference
UCS_Backend.Controllers.ScheduleController Class Reference
Public Member Functions
ScheduleController (IScheduleRepository scheduleRepository, IScheduleManager scheduleManager, IClassRepository classRepository, IRoomRepository roomRepository, ITimeRepository timeRepository, IWeekdayRepository weekdayRepository, ICrossRepository crossRepository, IInstructorRepository instructorRepository, IInstructorClassRepository instructorClassRepository)
IEnumerable< Schedule > GetAllSchedules ()
get all schedules
Schedule AddSchedule ([FromBody] ScheduleFormBody body)
void ParseCSV ()
creates list for csv file
Detailed Description
Creates a class for ScheduleController
Constructor & Destructor Documentation
ScheduleController()
UCS_Backend.Controllers.ScheduleController.ScheduleController (IScheduleRepository scheduleRepository, IScheduleManager scheduleManager, IClassRepository classRepository, IRoomRepository roomRepository, ITimeRepository timeRepository, IWeekdayRepository weekdayRepository, ICrossRepository crossRepository, IInstructorRepository instructorRepository, IInstructorClassRepository instructorClassRepository)
Creates method for controller scheduling
Parameters
scheduleRepository creates schedule repo
scheduleManager creates schedule manager repo
classRepository creates classroom repo
roomeRepository creates room repo
timeRepository creates time space for repo
weekdayRepository creates week days repo
crossRepository creates cross listing repo
instructorRepository creates instructor repo
instructorClassRepository creates instuctors class repo
Member Function Documentation
AddSchedule()
Schedule UCS_Backend.Controllers.ScheduleController.AddSchedule ([FromBody] ScheduleFormBody body)
adds schedule from body
Parameters
body
Returns
References UCS_Backend.Interfaces.IManagers.IScheduleManager.AddSchedule().
GetAllSchedules()
IEnumerable< Schedule > UCS_Backend.Controllers.ScheduleController.GetAllSchedules ()
get all schedules
Returns
References UCS_Backend.Interfaces.IScheduleRepository.GetAllSchedules().
ParseCSV()
void UCS_Backend.Controllers.ScheduleController.ParseCSV ()
creates list for csv file
References UCS_Backend.Utils.CSVParser.process(), and UCS_Backend.Utils.CSVParser.processBaseFiles().
The documentation for this class was generated from the following file:
UCS_Backend/Controllers/ScheduleController.cs