UCS_Backend: UCS_Backend.Utils.CSVParser Class Reference
UCS_Backend.Utils.CSVParser Class Reference
Creates a class for CSVParser
Public Member Functions
CSVParser (IClassRepository classRepository, IRoomRepository roomRepository, ITimeRepository timeRepository, IWeekdayRepository weekdayRepository, ICrossRepository crossRepository, IScheduleRepository scheduleRepository, IInstructorRepository instructorRepository, IInstructorClassRepository instructorClassRepository)
Dictionary< string, List< string[]> > processBaseFiles (List< string > inFiles)
void process (Dictionary< string, List< string[]> > inData)
int validateMilitaryTime (int militaryTime)
int convertToMilitary (string stdTime)
string weekdayConverter (string shorthand)
Public Attributes
Dictionary< string, string > dayMappings
Detailed Description
Creates a class for CSVParser
Constructor & Destructor Documentation
CSVParser()
UCS_Backend.Utils.CSVParser.CSVParser (IClassRepository classRepository, IRoomRepository roomRepository, ITimeRepository timeRepository, IWeekdayRepository weekdayRepository, ICrossRepository crossRepository, IScheduleRepository scheduleRepository, IInstructorRepository instructorRepository, IInstructorClassRepository instructorClassRepository)
Member Function Documentation
convertToMilitary()
int UCS_Backend.Utils.CSVParser.convertToMilitary (string stdTime)
Referenced by UCS_Backend.Utils.CSVParser.process().
process()
void UCS_Backend.Utils.CSVParser.process (Dictionary< string, List< string[]> > inData)
References UCS_Backend.Interfaces.IBaseRepository< T >.Add(), UCS_Backend.Interfaces.IRepositories.IClassRepository.AddNewClass(), UCS_Backend.Utils.CSVParser.convertToMilitary(), UCS_Backend.Interfaces.IRepositories.IClassRepository.FindClssID(), UCS_Backend.Models.Room.RoomId, UCS_Backend.Utils.CSVParser.validateMilitaryTime(), and UCS_Backend.Utils.CSVParser.weekdayConverter().
Referenced by UCS_Backend.Controllers.ScheduleController.ParseCSV().
processBaseFiles()
Dictionary< string, List< string[]> > UCS_Backend.Utils.CSVParser.processBaseFiles (List< string > inFiles)
Referenced by UCS_Backend.Controllers.ScheduleController.ParseCSV().
validateMilitaryTime()
int UCS_Backend.Utils.CSVParser.validateMilitaryTime (int militaryTime)
Referenced by UCS_Backend.Utils.CSVParser.process().
weekdayConverter()
string UCS_Backend.Utils.CSVParser.weekdayConverter (string shorthand)
References UCS_Backend.Utils.CSVParser.dayMappings.
Referenced by UCS_Backend.Utils.CSVParser.process().
Member Data Documentation
dayMappings
Dictionary<string, string> UCS_Backend.Utils.CSVParser.dayMappings
Initial value:
= new Dictionary<string, string> {
            {"M", "Monday"},
            {"T", "Tuesday"},
            {"W", "Wednesday"},
            {"Th", "Thursday"},
            {"F", "Friday"},
            {"Sa", "Satruday"},
            {"Su", "Sunday"}
        }
Referenced by UCS_Backend.Utils.CSVParser.weekdayConverter().
The documentation for this class was generated from the following file:
UCS_Backend/Utils/CSVParser.cs