UCS_Backend: UCS_Backend.Controllers.IndividualController Class Reference
UCS_Backend.Controllers.IndividualController Class Reference
Creates a class for IndividualController
Public Member Functions
IndividualController (IIndividualRepository individualRepository)
individual repo created
async Task< ActionResult< IEnumerable< Individual > > > GetAllIndividuals ()
get all individuals
async Task< ActionResult< Individual?> > GetIndividualById (int id)
get individuals by individual_id
async Task< ActionResult< Individual > > AddIndividual (Individual individual)
async Task< ActionResult<(bool, Individual)> > UpdateIndividual (Individual individual)
updates individual
async Task< ActionResult< bool > > DeleteIndividual (Individual individual)
deletes individual
Detailed Description
Creates a class for IndividualController
Constructor & Destructor Documentation
IndividualController()
UCS_Backend.Controllers.IndividualController.IndividualController (IIndividualRepository individualRepository)
individual repo created
Parameters
individualRepository
Member Function Documentation
AddIndividual()
async Task< ActionResult< Individual > > UCS_Backend.Controllers.IndividualController.AddIndividual (Individual individual)
add individuals
Parameters
individual
Returns
References UCS_Backend.Interfaces.IIndividualRepository.AddIndividual().
DeleteIndividual()
async Task< ActionResult< bool > > UCS_Backend.Controllers.IndividualController.DeleteIndividual (Individual individual)
deletes individual
Parameters
individual
Returns
References UCS_Backend.Interfaces.IIndividualRepository.DeleteIndividual().
GetAllIndividuals()
async Task< ActionResult< IEnumerable< Individual > > > UCS_Backend.Controllers.IndividualController.GetAllIndividuals ()
get all individuals
Returns
References UCS_Backend.Interfaces.IIndividualRepository.GetAllIndividuals().
GetIndividualById()
async Task< ActionResult< Individual?> > UCS_Backend.Controllers.IndividualController.GetIndividualById (int id)
get individuals by individual_id
Parameters
id
Returns
References UCS_Backend.Interfaces.IIndividualRepository.GetIndividualById().
UpdateIndividual()
async Task< ActionResult<(bool, Individual)> > UCS_Backend.Controllers.IndividualController.UpdateIndividual (Individual individual)
updates individual
Parameters
individual
Returns
References UCS_Backend.Interfaces.IIndividualRepository.UpdateIndividual().
The documentation for this class was generated from the following file:
UCS_Backend/Controllers/IndividualController.cs