UCS_Backend: UCS_Backend.Repositories.ScheduleRepository Class Reference
UCS_Backend.Repositories.ScheduleRepository Class Reference
Creates a class for ScheduleRepositoty
Public Member Functions
ScheduleRepository (DataContext dataContext, IRoomRepository roomRepository, ITimeRepository timeRepository, IInstructorRepository instructorRepository, IClassRepository classRepository, IWeekdayRepository weekdayRepository, IInstructorClassRepository instructorClassRepository)
Schedule Add (Schedule s)
add scheduled added
void Delete (Schedule entity)
delete schedule added
Schedule? FindById (int id)
finds schedule by id
List< Schedule > GetAllSchedules ()
puts schedule into a list format
void Update (Schedule entity)
updates schedule sheet
SuccessInfo ValidateInsert (AddClassModel addClassModel)
void AddClass (AddClassModel addClassModel)
Schedule AddUpdateSchedule (Schedule schedule)
List< Schedule > GetAllSchedules ()
SuccessInfo ValidateInsert (AddClassModel addClassModel)
void AddClass (AddClassModel addClassModel)
Public Member Functions inherited from UCS_Backend.Interfaces.IBaseRepository< Schedule >
T Add (T entity)
void Update (T entity)
void Delete (T entity)
T? FindById (int id)
Properties
IEnumerable< Schedule > GetAll [get]
Properties inherited from UCS_Backend.Interfaces.IBaseRepository< Schedule >
IEnumerable< T > GetAll [get]
Detailed Description
Creates a class for ScheduleRepositoty
Constructor & Destructor Documentation
ScheduleRepository()
UCS_Backend.Repositories.ScheduleRepository.ScheduleRepository (DataContext dataContext, IRoomRepository roomRepository, ITimeRepository timeRepository, IInstructorRepository instructorRepository, IClassRepository classRepository, IWeekdayRepository weekdayRepository, IInstructorClassRepository instructorClassRepository)
Member Function Documentation
Add()
Schedule UCS_Backend.Repositories.ScheduleRepository.Add (Schedule s)
add scheduled added
Parameters
s
Returns
References UCS_Backend.Models.Schedule.ClassId, UCS_Backend.Models.Schedule.RoomId, UCS_Backend.Data.DataContext.Schedules, UCS_Backend.Models.Schedule.TimeId, and UCS_Backend.Models.Schedule.WeekdayId.
AddClass()
void UCS_Backend.Repositories.ScheduleRepository.AddClass (AddClassModel addClassModel)
Parameters
addClassModel
Returns
Exceptions
NotImplementedException
Implements UCS_Backend.Interfaces.IScheduleRepository.
References UCS_Backend.Interfaces.IRepositories.IInstructorClassRepository.AddUpdateInstructorClass(), UCS_Backend.Repositories.ScheduleRepository.AddUpdateSchedule(), UCS_Backend.Models.AddClassModel.ClassEnd, UCS_Backend.Models.AddClassModel.ClassStart, UCS_Backend.Models.AddClassModel.CourseNumber, UCS_Backend.Models.AddClassModel.Days, UCS_Backend.Models.AddClassModel.Enrollment, UCS_Backend.Interfaces.IRepositories.IClassRepository.GetClassIdByCourseAndSection(), UCS_Backend.Interfaces.IInstructorRepository.GetInstuctorId(), UCS_Backend.Interfaces.IRepositories.IRoomRepository.GetRoomIdByRoomName(), UCS_Backend.Interfaces.IRepositories.ITimeRepository.GetTimeId(), UCS_Backend.Interfaces.IRepositories.IWeekdayRepository.GetWeekDaysIdByDescription(), UCS_Backend.Models.AddClassModel.InstructorName, UCS_Backend.Models.AddClassModel.RoomCode, UCS_Backend.Models.AddClassModel.RoomNumber, and UCS_Backend.Models.AddClassModel.SectionNumber.
Referenced by UCS_Backend.Repositories.ScheduleRepository.ValidateInsert().
AddUpdateSchedule()
Schedule UCS_Backend.Repositories.ScheduleRepository.AddUpdateSchedule (Schedule schedule)
Parameters
schedule
Returns
References UCS_Backend.Models.Schedule.ClassId, UCS_Backend.Models.Schedule.RoomId, UCS_Backend.Data.DataContext.Schedules, UCS_Backend.Models.Schedule.TimeId, and UCS_Backend.Models.Schedule.WeekdayId.
Referenced by UCS_Backend.Repositories.ScheduleRepository.AddClass().
Delete()
void UCS_Backend.Repositories.ScheduleRepository.Delete (Schedule entity)
delete schedule added
Parameters
entity
FindById()
Schedule? UCS_Backend.Repositories.ScheduleRepository.FindById (int id)
finds schedule by id
Parameters
id
Returns
GetAllSchedules()
List< Schedule > UCS_Backend.Repositories.ScheduleRepository.GetAllSchedules ()
puts schedule into a list format
Returns
Implements UCS_Backend.Interfaces.IScheduleRepository.
References UCS_Backend.Data.DataContext.Schedules.
Update()
void UCS_Backend.Repositories.ScheduleRepository.Update (Schedule entity)
updates schedule sheet
Parameters
entity
ValidateInsert()
SuccessInfo UCS_Backend.Repositories.ScheduleRepository.ValidateInsert (AddClassModel addClassModel)
Implements UCS_Backend.Interfaces.IScheduleRepository.
References UCS_Backend.Repositories.ScheduleRepository.AddClass(), UCS_Backend.Models.AddClassModel.ClassEnd, UCS_Backend.Models.AddClassModel.ClassStart, UCS_Backend.Models.AddClassModel.CourseNumber, UCS_Backend.Models.AddClassModel.Days, UCS_Backend.Models.AddClassModel.Enrollment, UCS_Backend.Models.AddClassModel.InstructorName, UCS_Backend.Models.AddClassModel.RoomCode, UCS_Backend.Models.AddClassModel.RoomNumber, UCS_Backend.Data.DataContext.Rooms, UCS_Backend.Models.AddClassModel.SectionNumber, and UCS_Backend.Models.SubModels.ScheduleInfo.StartTime.
Property Documentation
GetAll
IEnumerable<Schedule> UCS_Backend.Repositories.ScheduleRepository.GetAll get
The documentation for this class was generated from the following file:
UCS_Backend/Repositories/ScheduleRepository.cs