UCS_Backend: UCS_Backend.Interfaces.IRepositories.IRoomRepository Interface Reference
UCS_Backend.Interfaces.IRepositories.IRoomRepository Interface Reference
creates class for room repo to find room id by name
Public Member Functions
int FindRoomIdByName (string name)
List< ScheduleInfo > GetScheduleByRoomNumber (int roomNumber)
int GetRoomIdByRoomName (string buildingCode, string roomNumber)
Public Member Functions inherited from UCS_Backend.Interfaces.IBaseRepository< Room >
T Add (T entity)
void Update (T entity)
void Delete (T entity)
T? FindById (int id)
Additional Inherited Members
Properties inherited from UCS_Backend.Interfaces.IBaseRepository< Room >
IEnumerable< T > GetAll [get]
Detailed Description
creates class for room repo to find room id by name
Member Function Documentation
FindRoomIdByName()
int UCS_Backend.Interfaces.IRepositories.IRoomRepository.FindRoomIdByName (string name)
Implemented in UCS_Backend.Repositories.RoomRepository.
Referenced by UCS_Backend.BLL.ScheduleManager.AddSchedule().
GetRoomIdByRoomName()
int UCS_Backend.Interfaces.IRepositories.IRoomRepository.GetRoomIdByRoomName (string buildingCode, string roomNumber)
Implemented in UCS_Backend.Repositories.RoomRepository.
Referenced by UCS_Backend.Repositories.ScheduleRepository.AddClass().
GetScheduleByRoomNumber()
List< ScheduleInfo > UCS_Backend.Interfaces.IRepositories.IRoomRepository.GetScheduleByRoomNumber (int roomNumber)
Implemented in UCS_Backend.Repositories.RoomRepository.
Referenced by UCS_Backend.Controllers.RoomController.GetScheduleByRoomNumber().
The documentation for this interface was generated from the following file:
UCS_Backend/Interfaces/IRepositories/IRoomRepository.cs