UCS_Backend: UCS_Backend.Interfaces.IBaseRepository< T > Interface Template Reference
UCS_Backend.Interfaces.IBaseRepository< T > Interface Template Reference
creates class for base repo to pass Updates / Delete / FindById
Public Member Functions
T Add (T entity)
void Update (T entity)
void Delete (T entity)
T? FindById (int id)
Properties
IEnumerable< T > GetAll [get]
Detailed Description
creates class for base repo to pass Updates / Delete / FindById
Template Parameters
T
Type Constraints
T : class
Member Function Documentation
Add()
T UCS_Backend.Interfaces.IBaseRepository< T >.Add (T entity)
Referenced by UCS_Backend.Controllers.InstructorController.Add(), UCS_Backend.Controllers.RoomController.Add(), and UCS_Backend.Utils.CSVParser.process().
Delete()
void UCS_Backend.Interfaces.IBaseRepository< T >.Delete (T entity)
FindById()
T? UCS_Backend.Interfaces.IBaseRepository< T >.FindById (int id)
Update()
void UCS_Backend.Interfaces.IBaseRepository< T >.Update (T entity)
Property Documentation
GetAll
IEnumerable<T> UCS_Backend.Interfaces.IBaseRepository< T >.GetAll get
The documentation for this interface was generated from the following file:
UCS_Backend/Interfaces/IRepositories/IBaseRepository.cs